#!/usr/bin/env python3
import re
import sys 
from sploitkit import *
from tinyscript.helpers import is_bool, ExpiringDict, Path
from tinyscript import *

class GAMMA(FrameworkConsole):
    exclude = ["root/test", "root/help"]
    sources = {'banners': "banners"}
    
__all__ = ["GAMMA"]
__script__ = "GAMMA"
__doc__    = """
Launches GAMMA!
"""

if __name__ == '__main__':
    parser.add_argument("-d", "--dev", action="store_true", help="enable development mode")
    parser.add_argument("-v", "--verbose", action="store_true", help="enable verbose/debug mode")
    initialize(exit_at_interrupt=False)
    args = parser.parse_args()



    sys.tracebacklimit=0

    sys.dont_write_bytecode = True

    c = GAMMA(
        "GAMMA",

        banner_section_styles={'title': {'fgcolor': "lolcat"}},
        dev=args.dev,
        debug=args.verbose,
    )
    c.start()